services:
  wd-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wd-chatbot-dev
    ports:
      - "8080:80"
    volumes:
      - .:/app
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port=80
