openapi: 3.0.3
info:
  title: VMS_API
  version: 1.0.0
  description: |
    The VMS API allows fetching a list of residents filtered by parameters such as name and ID.
servers:
  - url: https://outdev.werkdone.com/VMS_BL/rest/ChatBot/v1
    description: Development environment
paths:
  /residents:
    get:
      summary: Get Resident Information
      description: |
        Retrieve a list of residents based on query parameters such as name and ID. The response includes detailed resident data, including personal details, admission date, status, and location. Additionally, it contains visitor-related information for each resident, such as relationships, visitation permissions, and caregiver details.
      operationId: Resident
      tags:
        - VMS_API
      parameters:
        - name: name
          in: query
          description: Filter residents by name.
          required: false
          schema:
            type: string
            example: Figarland
        - name: id
          in: query
          description: Filter residents by ID.
          required: false
          schema:
            type: string
            example: 695412b0-7c7b-4887-8494-317883816cdb
      responses:
        "200":
          description: A successful response containing resident information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResidentResponse"
  /visitors:
    get:
      summary: Get Visitor Information
      description: |
        Retrieve a list of visitors based on query parameters such as name and ID. The response includes visitor details, such as personal information, contact details, and related metadata.
      operationId: Visitor
      tags:
        - VMS_API
      parameters:
        - name: name
          in: query
          description: Filter visitors by name.
          required: false
          schema:
            type: string
            example: Carol
        - name: id
          in: query
          description: Filter visitors by ID.
          required: false
          schema:
            type: string
            example: a38d8e04-4d1f-438d-a5d8-76e183178e12
      responses:
        "200":
          description: A successful response containing visitor information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VisitorResponse"
  /visitations:
    get:
      summary: Get Visitation Information
      description: |
        Retrieve a list of visitations based on query parameters such as date, visitor ID, and resident ID. The response includes detailed visitation records, including date, time, visitation status, and associated resident and visitor information.
      operationId: Visitation
      tags:
        - VMS_API
      parameters:
        - name: date
          in: query
          description: Filter visitations by specific date.
          required: false
          schema:
            type: string
            format: date
            example: 2024-10-08
        - name: startDate
          in: query
          description: Filter visitations starting from this date.
          required: false
          schema:
            type: string
            format: date
            example: 2024-10-01
        - name: endDate
          in: query
          description: Filter visitations up to this date.
          required: false
          schema:
            type: string
            format: date
            example: 2024-10-31
        - name: status
          in: query
          description: Filter visitations by status.
          required: false
          schema:
            type: string
            example: Active
        - name: visitorId
          in: query
          description: Filter visitations by visitor ID.
          required: false
          schema:
            type: string
            example: a5799a8a-8e07-420c-8c6d-de952cdebdd3
        - name: residentId
          in: query
          description: Filter visitations by resident ID.
          required: false
          schema:
            type: string
            example: 695412b0-7c7b-4887-8494-317883816cdb
      responses:
        "200":
          description: A successful response containing visitation information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VisitationResponse"
  /visitor-availability:
    get:
      summary: Check Visitor Availability
      description: |
        Retrieve the availability status of a visitor based on optional query parameters such as name and ID.
        The response includes the resident they are visiting, the assigned timeslot, and any remarks about their visit.
      operationId: VisitorAvailability
      tags:
        - VMS_API
      parameters:
        - name: id
          in: query
          description: Filter visitor availability by ID.
          required: false
          schema:
            type: string
            example: a38d8e04-4d1f-438d-a5d8-76e183178e12
        - name: name
          in: query
          description: Filter visitor availability by name.
          required: false
          schema:
            type: string
            example: Carol Susetyo
      responses:
        "200":
          description: A successful response containing visitor availability information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VisitorAvailabilityResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResidentResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            residentlist:
              type: array
              items:
                $ref: "#/components/schemas/Resident_Object"
            count:
              type: integer
              example: 1
    VisitorResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            visitorlist:
              type: array
              items:
                $ref: "#/components/schemas/Visitor_Object"
            count:
              type: integer
              example: 1
    VisitationResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            visitationlist:
              type: array
              items:
                $ref: "#/components/schemas/Visitation_Object"
            count:
              type: integer
              example: 4
    VisitorAvailabilityResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            ResidentId:
              $ref: "#/components/schemas/ListItem_Object"
            Timeslot:
              type: string
              example: "10:00 - 19:00"
            Remarks:
              type: string
              example: "Denied by Outside Access Time."
    Resident_Object:
      type: object
      properties:
        Id:
          type: string
          example: 695412b0-7c7b-4887-8494-317883816cdb
        Name:
          type: string
          example: Figarland Garling
        CaseId:
          type: string
          example: 678D
        NRIC:
          type: string
          example: 678D
        AdmissionDate:
          type: string
          format: date
          example: 2024-10-04
        ClientId:
          type: string
          example: 4a687d93-5a89-4b01-a03d-f01fc2b0610f
        Layer1Id:
          type: string
          example: 09cac92d-4606-4e48-8311-fbd014f4b05c
        BedId:
          type: string
          example: 9509c68d-8915-4421-a49f-892d480c18ac
        CreatedAt:
          type: string
          format: date-time
          example: 2024-10-04T03:04:58Z
        ModifiedAt:
          type: string
          format: date-time
          example: 2024-10-04T03:04:58Z
        IsAllowedToBeVisited:
          type: boolean
          example: true
        Location:
          type: string
          example: 6A13
        Visitor:
          type: array
          items:
            $ref: "#/components/schemas/ResidentVisitor_Object"
    Visitor_Object:
      type: object
      properties:
        Id:
          type: string
          example: a38d8e04-4d1f-438d-a5d8-76e183178e12
        Name:
          type: string
          example: Carol Susetyo
        PhoneCountryCode:
          type: string
          example: 65
        PhoneCountryIso:
          type: string
          example: sg
        PhoneNumber:
          type: string
          example: 7013456124
        Email:
          type: string
          example: carol@mail.com
        IsActive:
          type: boolean
          example: true
        CreatedAt:
          type: string
          format: date-time
          example: 2024-08-01T02:07:41Z
        ModifiedAt:
          type: string
          format: date-time
          example: 2024-12-06T08:24:20Z
        BranchId:
          type: string
          example: 09cac92d-4606-4e48-8311-fbd014f4b05c
        ClientId:
          type: string
          example: 4a687d93-5a89-4b01-a03d-f01fc2b0610f
        VMSUserTypeId:
          type: string
          example: Staff
        VMSUserSubTypeId:
          type: string
          example: SLEC
    ResidentVisitor_Object:
      type: object
      description: Details about the relationship between a resident and a visitor.
      properties:
        Id:
          type: string
          default: ""
        ResidentId:
          $ref: "#/components/schemas/ListItem_Object"
        VisitorId:
          $ref: "#/components/schemas/ListItem_Object"
        IsMainVisitor:
          type: boolean
          example: false
        IsAllowedToVisit:
          type: boolean
          example: false
        IsActive:
          type: boolean
          example: false
        IsDeleted:
          type: boolean
          example: false
        CreatedAt:
          type: string
          format: date-time
          example: "2014-12-31T23:59:59.938Z"
        ModifiedAt:
          type: string
          format: date-time
          example: "2014-12-31T23:59:59.938Z"
        Relationship:
          type: string
          default: ""
        IsCaregiver:
          type: boolean
          example: false
        CaregiverStartTime:
          type: string
          format: date-time
          example: "2014-12-31T23:59:59.938Z"
        CaregiverEndTime:
          type: string
          format: date-time
          example: "2014-12-31T23:59:59.938Z"
    Visitation_Object:
      type: object
      properties:
        Id:
          type: string
          example: 013840b2-267e-4128-9da0-d8a44c6c6728
        VMSUserId:
          type: object
          properties:
            Id:
              type: string
              example: a5799a8a-8e07-420c-8c6d-de952cdebdd3
            Name:
              type: string
              example: Shanks
        CardNumber:
          type: string
          example: ZFRLnCfw72
        Date:
          type: string
          format: date
          example: 2024-10-08
        BeginDateTime:
          type: string
          format: date-time
          example: 2024-10-08T07:00:00Z
        EndDateTime:
          type: string
          format: date-time
          example: 2024-10-08T08:00:00Z
        CreatedAt:
          type: string
          format: date-time
          example: 2024-10-04T03:05:33Z
        ModifiedAt:
          type: string
          format: date-time
          example: 2024-10-04T03:32:54Z
        ClientId:
          type: string
          example: 4a687d93-5a89-4b01-a03d-f01fc2b0610f
        BranchId:
          type: string
          example: 09cac92d-4606-4e48-8311-fbd014f4b05c
        VisitationTypeId:
          type: string
          example: 52938711-fc32-4e5d-ac04-b0f43381ff72
        VisitationStatusId:
          type: string
          example: 0e5c4fdb-fd79-4657-8c53-0317ab280ee9
        TimeslotId:
          type: string
          example: a0e501b4-6b71-4caa-940a-118b3370ca12
        ResidentId:
          type: object
          properties:
            Id:
              type: string
              example: 695412b0-7c7b-4887-8494-317883816cdb
            Name:
              type: string
              example: Figarland Garling
    ListItem_Object:
      type: object
      properties:
        Id:
          type: string
          default: ""
        Name:
          type: string
          default: ""
