name: publish

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:latest

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  deploy:
      name: Deploy Image
      needs: publish
      runs-on: self-hosted

      steps:
      - name: Deploy with Docker Compose
        run: |
          cd ${{ secrets.WORK_DIR }}
          docker compose pull
          docker compose up -d
    
